name: Pages Deployment

on:
  push:
    branches: [master]

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd src/web && npm ci
      - run: cd src/web && npm run ghbuild

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: src/web/out